---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak-config-cli.realmConfigMap" . }}
  labels:
  {{- include "keycloak-config-cli.labels" . | nindent 4 }}
data:
  {{- range $name, $config := .Values.config }}
    {{- if hasKey $config "file" }}
  {{ $name }}.json: |
    {{- tpl ($.Files.Get $config.file) $ | trim | nindent 4 }}
    {{- else if hasKey $config "inline" }}
  {{ $name }}.json: |
    {{- tpl (toJson $config.inline) $ | trim | nindent 4 }}
    {{- end }}
  {{- end }}
