{{- if .Values.voilaSvcClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: voila-svc-keycloak
  labels:
    {{- include "voila.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_VOILA_SVC_CLIENT_SECRET: {{ .Values.voilaSvcClientSecret | quote }}
{{- end }}
