#!/usr/bin/env python3
"""CI check for the on-prem secret contract (validate-deploy.yaml).

Renders ``deploy/base/secrets-on-prem`` through ``flux build kustomization --dry-run``,
which runs kustomize-controller's own re-serialize-then-substitute code offline, and
fails unless:

1. every key renders to exactly its intended string, for the fixture values and for a
   hostile set that any unwrapped placeholder would mis-type or truncate;
2. strict substitution rejects a missing secret value or cluster-var by name;
3. every template carries prune: disabled (the CNPG ones also cnpg.io/reload), and no
   template has a bare $ that Flux would leave literal;
4. every Secret (and key) the on-prem Flux paths reference is provided in the right
   namespace (templated, generated by a base, or issued by a Certificate), and every
   template has a consumer;
5. each CNPG managed role's Secret carries that role's name as its username.

``flux build`` masks and re-types Secret values when it prints them, so values are
asserted on ConfigMap twins of the templates. Needs flux and kustomize on PATH, and
never touches a cluster.
"""

from __future__ import annotations

import collections
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

from gen_cluster_vars import build as build_cluster_vars
from gen_cluster_vars import load_required
from gen_secret_values import validate

HERE = Path(__file__).resolve().parent
DEPLOY = HERE.parents[1] / "deploy"
TEMPLATES = DEPLOY / "base" / "secrets-on-prem"
GATE = DEPLOY / "modes" / "on-prem" / "secrets.yaml"
# $$ is Flux's escape for a literal $; ${name} and ${name:=default} are substituted.
VAR = re.compile(r"\$\$|\$\{([_A-Za-z][_A-Za-z0-9]*)(:=([^}]*))?\}")
SQ = "${sq}"

# Templates whose consumer reads a chart-default Secret name, so no base spells it
# out; they count as consumed while that HelmRelease is part of the on-prem set.
CHART_DEFAULT_CONSUMERS = {
    "superset-env": "superset",
    "superset-valkey-auth": "scout-dashboards",
}
# Where bases name a Secret: {name: ...} refs (with an optional key), plain-string
# chart values, and lists of {name: ...}.
REF_KEYS = {
    "secretKeyRef",
    "secretRef",
    "secret",
    "passwordSecret",
    "superuserSecret",
    "usernameSecret",
    "configSecret",
    "passwordSecretRef",
}
STR_KEYS = {
    "secret",
    "secretName",
    "existingSecret",
    "usersExistingSecret",
    "existingNextAuthSecret",
    "envFromSecret",
    "trinoCaSecret",
}
LIST_KEYS = {"extraExporterSecrets"}
# A chart value naming the key read from its sibling existingSecret.
SIBLING_KEYS = {"secretKey", "existingSecretKey"}


def kustomize_build(path) -> list:
    out = subprocess.run(
        ["kustomize", "build", str(path)], capture_output=True, text=True, check=True
    ).stdout
    return [d for d in yaml.safe_load_all(out) if d]


def var_names(text: str) -> set:
    return {m[0] for m in VAR.findall(text) if m[0]}


def subst(text: str, env: dict) -> str:
    """Flux's semantics: ${v:=d} takes d when v is unset or empty."""

    def rep(m):
        if m.group(0) == "$$":
            return "$"
        name, has_default, default = m.group(1), m.group(2), m.group(3)
        if name in env and (env[name] != "" or has_default is None):
            return env[name]
        if has_default is not None:
            return default
        raise KeyError(name)

    return VAR.sub(rep, text)


def intended(template_value: str, env: dict) -> str:
    """What a template value should render to: ${sq}...${sq} is a quote, nothing more."""
    if template_value.startswith(SQ) and template_value.endswith(SQ):
        template_value = template_value[len(SQ) : -len(SQ)]
    return subst(template_value, env)


def templates() -> list:
    docs = []
    for f in sorted(TEMPLATES.glob("*.yaml")):
        if f.name != "kustomization.yaml":
            docs.extend(d for d in yaml.safe_load_all(f.read_text()) if d)
    return docs


def flux_render(env: dict):
    """(objects, error) of the ConfigMap twins built + substituted by flux."""
    with tempfile.TemporaryDirectory() as tmp:
        tpl = Path(tmp, "tpl")
        shutil.copytree(TEMPLATES, tpl)
        for f in tpl.glob("*.yaml"):
            if f.name == "kustomization.yaml":
                continue
            text = f.read_text().replace("kind: Secret", "kind: ConfigMap")
            text = re.sub(r"(?m)^type: .*\n", "", text.replace("stringData:", "data:"))
            f.write_text(text)
        gate = yaml.safe_load(GATE.read_text())
        gate["spec"]["path"] = "./tpl"
        gate["spec"]["postBuild"] = {"substitute": env}
        Path(tmp, "ks.json").write_text(json.dumps(gate))
        p = subprocess.run(
            [
                "flux",
                "build",
                "kustomization",
                gate["metadata"]["name"],
                "--path",
                "./tpl",
                "--kustomization-file",
                "./ks.json",
                "--dry-run",
                "--strict-substitute",
            ],
            cwd=tmp,
            capture_output=True,
            text=True,
            env=dict(os.environ, KUBECONFIG=os.devnull),
        )
        if p.returncode:
            return None, p.stderr.strip()
        return [d for d in yaml.safe_load_all(p.stdout) if d], None


def check_render(env: dict, label: str) -> list:
    objs, err = flux_render(env)
    if err:
        return ["[{}] flux build failed: {}".format(label, err)]
    got = {
        (o["metadata"]["namespace"], o["metadata"]["name"]): o.get("data") or {}
        for o in objs
    }
    problems, n, docs = [], 0, templates()
    for d in docs:
        ident = (
            subst(d["metadata"]["namespace"], env),
            subst(d["metadata"]["name"], env),
        )
        data = got.pop(ident, None)
        if data is None:
            problems.append("[{}] {}/{} not rendered".format(label, *ident))
            continue
        for key, tmpl in d["stringData"].items():
            n += 1
            want = intended(tmpl, env)
            if data.get(key) != want or not isinstance(data.get(key), str):
                problems.append(
                    "[{}] {}/{}:{} renders {!r}, want {!r}".format(
                        label, ident[0], ident[1], key, data.get(key), want
                    )
                )
        problems += [
            "[{}] {}/{}:{} rendered but not templated".format(label, *ident, k)
            for k in sorted(set(data) - set(d["stringData"]))
        ]
    problems += ["[{}] {}/{} rendered but not templated".format(label, *i) for i in got]
    if not problems:
        print(
            "  ok   [{}] {} keys in {} Secrets render exactly".format(
                label, n, len(docs)
            )
        )
    return problems


def hostile(env: dict) -> dict:
    """Swap every value a template substitutes for one that breaks unless wrapped.

    Namespaces keep their real values; vars inside Secret names get octal-looking
    ones (0123 parses as an int); the rest get '0NNN #name: v', which an unwrapped
    placeholder truncates at the comment.
    """
    docs = templates()
    ns_vars = {v for d in docs for v in var_names(d["metadata"]["namespace"])}
    name_vars = {v for d in docs for v in var_names(d["metadata"]["name"])}
    used = {v for d in docs for s in d["stringData"].values() for v in var_names(s)}
    out = dict(env)
    for i, name in enumerate(sorted(used - ns_vars - {"sq"})):
        out[name] = (
            "0" + oct(8 + i)[2:]
            if name in name_vars
            else "0{:03d} #{}: v".format(i, name)
        )
    return out


def check_strict(env: dict) -> list:
    problems = []
    for name in ("postgres_password", "db_port"):
        _, err = flux_render({k: v for k, v in env.items() if k != name})
        if not err or '"{}"'.format(name) not in err:
            problems.append(
                "strict substitution did not reject a missing {}".format(name)
            )
        else:
            print("  ok   strict substitution rejects a missing {}".format(name))
    return problems


def check_metadata() -> list:
    problems = []
    for d in kustomize_build(TEMPLATES):
        md = d["metadata"]
        where = "{}/{}".format(md["namespace"], md["name"])
        if d["kind"] != "Secret":
            problems.append("{}: is a {}, not a Secret".format(where, d["kind"]))
        if (md.get("annotations") or {}).get(
            "kustomize.toolkit.fluxcd.io/prune"
        ) != "disabled":
            problems.append(
                "{}: missing kustomize.toolkit.fluxcd.io/prune: disabled".format(where)
            )
        cnpg = md["namespace"] == "${postgres_cluster_namespace}"
        if cnpg and (md.get("labels") or {}).get("cnpg.io/reload") != "true":
            problems.append(
                '{}: CNPG Secret without cnpg.io/reload: "true"'.format(where)
            )
        for key, value in [("name", md["name"]), ("namespace", md["namespace"])] + list(
            (d.get("stringData") or {}).items()
        ):
            if "$" in VAR.sub("", value):
                problems.append(
                    "{}:{}: bare $ (Flux substitutes only ${{...}})".format(where, key)
                )
    if not problems:
        print(
            "  ok   templates carry prune: disabled (CNPG: cnpg.io/reload); no bare $"
        )
    return problems


def on_prem_paths() -> list:
    """Paths of the on-prem Flux Kustomizations that render the scout-config artifact."""
    paths = set()
    for f in sorted((DEPLOY / "flux").glob("*.yaml")) + sorted(
        (DEPLOY / "modes" / "on-prem").glob("*.yaml")
    ):
        if f.name == "kustomization.yaml":
            continue
        for d in yaml.safe_load_all(f.read_text()):
            if (
                d
                and d["kind"] == "Kustomization"
                and d["spec"]["sourceRef"]["name"] == "scout-config"
            ):
                paths.add(os.path.normpath(d["spec"]["path"].lstrip("/")))
    return sorted(paths)


def check_coverage(cluster_vars: dict) -> list:
    """(namespace, name[, key]) refs in the on-prem bases vs what is provided."""
    refs = collections.defaultdict(set)  # (ns, name) -> {(key or None, where)}
    provided, helmreleases = set(), set()

    def ns_of(d):
        ns = d["metadata"].get("namespace", "")
        if d["kind"] == "HelmRelease":
            ns = d["spec"].get("targetNamespace") or ns
        return subst(ns, cluster_vars)

    def ref(ns, name, key, where):
        refs[(ns, subst(name, cluster_vars))].add((key, where))

    def walk(node, ns, where):
        if isinstance(node, dict):
            for k, v in node.items():
                if (
                    k in REF_KEYS
                    and isinstance(v, dict)
                    and isinstance(v.get("name"), str)
                ):
                    if not v.get("optional"):
                        ref(ns, v["name"], v.get("key"), where)
                elif k in STR_KEYS and isinstance(v, str) and v:
                    key = next(
                        (node[s] for s in SIBLING_KEYS if isinstance(node.get(s), str)),
                        None,
                    )
                    ref(ns, v, key, where)
                elif k in LIST_KEYS and isinstance(v, list):
                    for item in v:
                        ref(ns, item["name"], None, where)
                walk(v, ns, where)
        elif isinstance(node, list):
            for x in node:
                walk(x, ns, where)

    for path in on_prem_paths():
        if path == "base/secrets-on-prem":
            continue
        for d in kustomize_build(DEPLOY / path):
            ns, name = ns_of(d), subst(d["metadata"]["name"], cluster_vars)
            where = "{} {}/{}".format(path, d["kind"], name)
            if d["kind"] == "Secret":
                provided.add((ns, name))
            elif d["kind"] == "Certificate":
                provided.add((ns, subst(d["spec"]["secretName"], cluster_vars)))
            elif d["kind"] == "HelmRelease":
                helmreleases.add((ns, name))
            # Per-mode edge ConfigMaps carry Helm values as embedded YAML; only the
            # on-prem one is read here.
            if d["kind"] == "ConfigMap" and name.endswith("-edge-aws"):
                continue
            walk(d, ns, where)
            if d["kind"] == "ConfigMap":
                for key, text in (d.get("data") or {}).items():
                    if key.endswith((".yaml", ".yml")):
                        walk(yaml.safe_load(text), ns, where)

    templated = {}
    for d in templates():
        ident = (
            subst(d["metadata"]["namespace"], cluster_vars),
            subst(d["metadata"]["name"], cluster_vars),
        )
        templated[ident] = set(d["stringData"])
    problems = []
    for ident, uses in sorted(refs.items()):
        where = sorted(w for _, w in uses)[0]
        if ident in templated:
            problems += [
                "{}/{} has no key {} ({})".format(*ident, key, w)
                for key, w in sorted(uses, key=str)
                if key and key not in templated[ident]
            ]
        elif ident not in provided:
            problems.append(
                "{}/{} is referenced on-prem but nothing provides it ({})".format(
                    *ident, where
                )
            )
    for ident in sorted(set(templated) - set(refs)):
        if (ident[0], CHART_DEFAULT_CONSUMERS.get(ident[1])) not in helmreleases:
            problems.append("template {}/{} has no on-prem consumer".format(*ident))
    if not problems:
        print(
            "  ok   all {} templates have a consumer; every on-prem Secret ref is provided".format(
                len(templated)
            )
        )
    return problems


def check_cnpg_roles(env: dict) -> list:
    """CNPG rejects a role Secret whose username differs from the role name, and that
    aborts reconciliation of every managed role; a role without one gets no password."""
    by_name = {
        d["metadata"]["name"]: d
        for d in templates()
        if d["metadata"]["namespace"] == "${postgres_cluster_namespace}"
    }
    problems = []
    for cluster in (
        d
        for d in kustomize_build(DEPLOY / "base/postgres/cluster")
        if d["kind"] == "Cluster"
    ):
        want = [(cluster["spec"]["superuserSecret"]["name"], "postgres")]
        for role in cluster["spec"]["managed"]["roles"]:
            secret = (role.get("passwordSecret") or {}).get("name")
            if not secret:
                problems.append(
                    "CNPG role {} has no passwordSecret".format(role["name"])
                )
                continue
            want.append((secret, subst(role["name"], env)))
        for secret, user in want:
            tpl = by_name.get(secret)
            got = intended(tpl["stringData"]["username"], env) if tpl else None
            if got != user:
                problems.append(
                    "CNPG Secret {} has username {!r}, want {!r}".format(
                        secret, got, user
                    )
                )
    if not problems:
        print("  ok   every CNPG role Secret carries its role's name")
    return problems


def main() -> None:
    fixtures = HERE / "fixtures"
    cv_values = json.loads((fixtures / "cluster-vars.values.json").read_text())
    secret_values = json.loads((fixtures / "secret-values.values.json").read_text())
    contract = load_required(DEPLOY / "required-secret-values.txt")
    problems = [
        "fixture: " + p for p in validate(secret_values, cv_values, contract)[0]
    ]

    cluster_vars = build_cluster_vars(
        cv_values, load_required(DEPLOY / "required-vars.txt")
    )
    inline = yaml.safe_load(GATE.read_text())["spec"]["postBuild"]["substitute"]
    env = {**cluster_vars, **secret_values, **inline}
    problems += check_render(env, "fixture")
    problems += check_render(hostile(env), "hostile")
    problems += check_strict(env)
    problems += check_metadata()
    problems += check_coverage(cluster_vars)
    problems += check_cnpg_roles(env)
    for p in problems:
        print("::error::" + p)
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
