#!/usr/bin/env python3
"""CI check for the on-prem secret contract (validate-deploy.yaml).

Renders ``deploy/base/secrets-on-prem`` through ``flux build kustomization --dry-run``,
which runs kustomize-controller's own re-serialize-then-substitute code offline, and
fails unless:

1. every key renders to exactly its intended string, for the fixture values and for a
   hostile set that any unwrapped placeholder would mis-type or truncate;
2. strict substitution rejects a missing secret value or cluster-var by name;
3. every template carries prune: disabled, and the CNPG ones cnpg.io/reload;
4. every Secret the on-prem Flux paths reference is provided (templated, generated by a
   base, or issued by a Certificate), and every template has a consumer.

``flux build`` masks and re-types Secret values when it prints them, so values are
asserted on ConfigMap twins of the templates. Needs flux and kustomize on PATH, and
never touches a cluster.
"""

from __future__ import annotations

import collections
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

from gen_cluster_vars import build as build_cluster_vars
from gen_cluster_vars import load_required
from gen_secret_values import validate

HERE = Path(__file__).resolve().parent
DEPLOY = HERE.parents[1] / "deploy"
TEMPLATES = DEPLOY / "base" / "secrets-on-prem"
GATE = DEPLOY / "modes" / "on-prem" / "secrets.yaml"
VAR = re.compile(r"\$\{([_A-Za-z][_A-Za-z0-9]*)(:=([^}]*))?\}")
SQ = "${sq}"

# Templates whose consumer reads a chart-default Secret name, so no base spells it out.
CHART_DEFAULT_CONSUMERS = {
    "superset-env": "superset chart envFromSecret default",
    "superset-valkey-auth": "scout-dashboards chart import Job default",
}
# Where bases name a Secret: {key: {name: ...}} refs and plain-string chart values.
REF_KEYS = {
    "secretKeyRef",
    "secretRef",
    "secret",
    "passwordSecret",
    "superuserSecret",
    "usernameSecret",
    "configSecret",
    "passwordSecretRef",
}
STR_KEYS = {
    "secretName",
    "existingSecret",
    "usersExistingSecret",
    "existingNextAuthSecret",
    "envFromSecret",
}


def kustomize_build(path) -> list:
    out = subprocess.run(
        ["kustomize", "build", str(path)], capture_output=True, text=True, check=True
    ).stdout
    return [d for d in yaml.safe_load_all(out) if d]


def subst(text: str, env: dict) -> str:
    def rep(m):
        if m.group(1) in env:
            return env[m.group(1)]
        if m.group(2) is not None:
            return m.group(3)
        raise KeyError(m.group(1))

    return VAR.sub(rep, text)


def intended(template_value: str, env: dict) -> str:
    """What a template value should render to: ${sq}...${sq} is a quote, nothing more."""
    if template_value.startswith(SQ) and template_value.endswith(SQ):
        template_value = template_value[len(SQ) : -len(SQ)]
    return subst(template_value, env)


def templates() -> list:
    docs = []
    for f in sorted(TEMPLATES.glob("*.yaml")):
        if f.name != "kustomization.yaml":
            docs.extend(d for d in yaml.safe_load_all(f.read_text()) if d)
    return docs


def flux_render(env: dict):
    """(objects, error) of the ConfigMap twins built + substituted by flux."""
    with tempfile.TemporaryDirectory() as tmp:
        tpl = Path(tmp, "tpl")
        shutil.copytree(TEMPLATES, tpl)
        for f in tpl.glob("*.yaml"):
            if f.name == "kustomization.yaml":
                continue
            text = f.read_text().replace("kind: Secret", "kind: ConfigMap")
            text = re.sub(r"(?m)^type: .*\n", "", text.replace("stringData:", "data:"))
            f.write_text(text)
        gate = yaml.safe_load(GATE.read_text())
        gate["spec"]["path"] = "./tpl"
        gate["spec"]["postBuild"] = {"substitute": env}
        Path(tmp, "ks.json").write_text(json.dumps(gate))
        p = subprocess.run(
            [
                "flux",
                "build",
                "kustomization",
                gate["metadata"]["name"],
                "--path",
                "./tpl",
                "--kustomization-file",
                "./ks.json",
                "--dry-run",
                "--strict-substitute",
            ],
            cwd=tmp,
            capture_output=True,
            text=True,
            env=dict(os.environ, KUBECONFIG=os.devnull),
        )
        if p.returncode:
            return None, p.stderr.strip()
        return [d for d in yaml.safe_load_all(p.stdout) if d], None


def check_render(env: dict, label: str) -> list:
    objs, err = flux_render(env)
    if err:
        return ["[{}] flux build failed: {}".format(label, err)]
    got = {
        (o["metadata"]["namespace"], o["metadata"]["name"]): o.get("data") or {}
        for o in objs
    }
    problems, n = [], 0
    docs = templates()
    if len(got) != len(docs):
        problems.append(
            "[{}] rendered {} objects, want {}".format(label, len(got), len(docs))
        )
    for d in docs:
        ident = (
            subst(d["metadata"]["namespace"], env),
            subst(d["metadata"]["name"], env),
        )
        data = got.get(ident)
        if data is None:
            problems.append("[{}] {}/{} not rendered".format(label, *ident))
            continue
        for key, tmpl in d["stringData"].items():
            n += 1
            want = intended(tmpl, env)
            if not isinstance(data.get(key), str) or data[key] != want:
                problems.append(
                    "[{}] {}/{}:{} renders {!r}, want {!r}".format(
                        label, ident[0], ident[1], key, data.get(key), want
                    )
                )
        if set(data) != set(d["stringData"]):
            problems.append("[{}] {}/{} key set differs".format(label, *ident))
    if not problems:
        print(
            "  ok   [{}] {} keys in {} Secrets render exactly".format(
                label, n, len(docs)
            )
        )
    return problems


def hostile(env: dict) -> dict:
    """Swap every value a template substitutes for one that breaks unless wrapped.

    Namespaces keep their real values; vars inside Secret names get octal-looking
    ones (0123 parses as an int); the rest get '0NNN #name: v', which an unwrapped
    placeholder truncates at the comment.
    """
    docs = templates()
    ns_vars = {m[0] for d in docs for m in VAR.findall(d["metadata"]["namespace"])}
    name_vars = {m[0] for d in docs for m in VAR.findall(d["metadata"]["name"])}
    used = {
        m[0] for d in docs for v in d["stringData"].values() for m in VAR.findall(v)
    }
    out = dict(env)
    for i, name in enumerate(sorted(used - ns_vars - {"sq"})):
        out[name] = (
            "0" + oct(8 + i)[2:]
            if name in name_vars
            else "0{:03d} #{}: v".format(i, name)
        )
    return out


def check_strict(env: dict) -> list:
    problems = []
    for name in ("postgres_password", "db_port"):
        _, err = flux_render({k: v for k, v in env.items() if k != name})
        if not err or '"{}"'.format(name) not in err:
            problems.append(
                "strict substitution did not reject a missing {}".format(name)
            )
        else:
            print("  ok   strict substitution rejects a missing {}".format(name))
    return problems


def check_metadata() -> list:
    problems = []
    for d in kustomize_build(TEMPLATES):
        md, where = d["metadata"], "{}/{}".format(
            d["metadata"]["namespace"], d["metadata"]["name"]
        )
        if d["kind"] != "Secret":
            problems.append("{}: is a {}, not a Secret".format(where, d["kind"]))
        if (md.get("annotations") or {}).get(
            "kustomize.toolkit.fluxcd.io/prune"
        ) != "disabled":
            problems.append(
                "{}: missing kustomize.toolkit.fluxcd.io/prune: disabled".format(where)
            )
        cnpg = md["namespace"] == "${postgres_cluster_namespace}"
        if cnpg and (md.get("labels") or {}).get("cnpg.io/reload") != "true":
            problems.append(
                '{}: CNPG Secret without cnpg.io/reload: "true"'.format(where)
            )
    if not problems:
        print(
            "  ok   every template has prune: disabled; CNPG ones have cnpg.io/reload"
        )
    return problems


def _on_prem_paths() -> set:
    paths = set()
    for f in sorted((DEPLOY / "flux").glob("*.yaml")) + sorted(
        (DEPLOY / "modes" / "on-prem").glob("*.yaml")
    ):
        if f.name == "kustomization.yaml":
            continue
        for d in yaml.safe_load_all(f.read_text()):
            if (
                d
                and d["kind"] == "Kustomization"
                and d["spec"]["path"].startswith("./base/")
            ):
                paths.add(d["spec"]["path"])
    return paths


def check_coverage() -> list:
    refs, provided = collections.defaultdict(set), set()

    def walk(node, where):
        if isinstance(node, dict):
            for k, v in node.items():
                if (
                    k in REF_KEYS
                    and isinstance(v, dict)
                    and isinstance(v.get("name"), str)
                ):
                    if not v.get("optional"):
                        refs[v["name"]].add(where)
                elif k in STR_KEYS and isinstance(v, str) and v:
                    refs[v].add(where)
                walk(v, where)
        elif isinstance(node, list):
            for x in node:
                walk(x, where)

    for path in sorted(_on_prem_paths()):
        if path == "./base/secrets-on-prem":
            continue
        for d in kustomize_build(DEPLOY / path[2:]):
            where = "{} {}/{}".format(path, d["kind"], d["metadata"]["name"])
            if d["kind"] == "Secret":
                provided.add(d["metadata"]["name"])
            if d["kind"] == "Certificate":
                provided.add(d["spec"]["secretName"])
            walk(d, where)
            # per-mode edge ConfigMaps carry Helm values as embedded YAML
            if d["kind"] == "ConfigMap":
                for key, text in (d.get("data") or {}).items():
                    if key.endswith((".yaml", ".yml")):
                        walk(yaml.safe_load(text), where)
    templated = {d["metadata"]["name"] for d in templates()}
    problems = [
        "{} is referenced on-prem but no template provides it ({})".format(
            n, sorted(refs[n])[0]
        )
        for n in sorted(set(refs) - templated - provided)
    ]
    problems += [
        "template {} has no on-prem consumer".format(n)
        for n in sorted(templated - set(refs) - set(CHART_DEFAULT_CONSUMERS))
    ]
    if not problems:
        print(
            "  ok   all {} template names have a consumer; every on-prem Secret ref is provided".format(
                len(templated)
            )
        )
    return problems


def main() -> None:
    fixtures = HERE / "fixtures"
    cv_values = json.loads((fixtures / "cluster-vars.values.json").read_text())
    secret_values = json.loads((fixtures / "secret-values.values.json").read_text())
    contract = load_required(DEPLOY / "required-secret-values.txt")
    problems = [
        "fixture: " + p for p in validate(secret_values, cv_values, contract)[0]
    ]

    cluster_vars = build_cluster_vars(
        cv_values, load_required(DEPLOY / "required-vars.txt")
    )
    inline = yaml.safe_load(GATE.read_text())["spec"]["postBuild"]["substitute"]
    env = {**cluster_vars, **secret_values, **inline}
    problems += check_render(env, "fixture")
    problems += check_render(hostile(env), "hostile")
    problems += check_strict(env)
    problems += check_metadata()
    problems += check_coverage()
    for p in problems:
        print("::error::" + p)
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
