apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "${oauth2_proxy_namespace}"
resources:
  - resources.yaml
configMapGenerator:
  - name: oauth2-proxy-templates
    files:
      - error.html
      - sign_in.html
generatorOptions:
  disableNameSuffixHash: true
