{
 "title": "JupyterHub",
 "description": "JupyterHub Monitoring",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Jupyter Servers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"jupyter-.*\"}) by (phase)",
     "legendFormat": "{% raw %}{{phase}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Jupyter Server CPU Usage by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"jupyter\", pod=~\"jupyter.*\"}[$__rate_interval]))",
     "legendFormat": "{% raw %}{{ pod }}{% endraw %}"
    }
   ]
  },
  {
   "title": "Jupyter Server Memory Usage by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"jupyter\", pod=~\"jupyter.*\"}) by (pod)",
     "legendFormat": "{% raw %}{{ pod }}{% endraw %}"
    }
   ]
  }
 ]
}