{
 "title": "Node Exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, node)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Quick CPU / Mem / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", node=\"$node\"}[5m])))"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "gauge",
   "description": "System load  over all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{node=\"$node\",job=\"$job\"}) * 100 / count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{node=\"$node\", job=\"$job\"} / node_memory_MemTotal_bytes{node=\"$node\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{node=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{node=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{node=\"$node\",job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{node=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{node=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{node=\"$node\",job=\"$job\"} - node_boot_time_seconds{node=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{node=\"$node\",job=\"$job\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"system\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"user\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"iowait\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=~\".*irq\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\",  mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"idle\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{node=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{node=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{node=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{node=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{node=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{node=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{node=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{node=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{node=\"$node\",job=\"$job\"}[5m])*8",
     "legendFormat": "{% raw %}recv {{device}}{% endraw %}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{node=\"$node\",job=\"$job\"}[5m])*8",
     "legendFormat": "{% raw %}trans {{device}}{% endraw %} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"} * 100) / node_filesystem_size_bytes{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"})",
     "legendFormat": "{% raw %}{{mountpoint}}{% endraw %}"
    }
   ]
  },
  { "title": "CPU / Memory / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"system\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"user\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"nice\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"iowait\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"irq\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"softirq\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"steal\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{node=\"$node\",job=\"$job\", mode=\"idle\"}[5m])) / scalar(count(count(node_cpu_seconds_total{node=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{node=\"$node\",job=\"$job\"} - node_memory_Buffers_bytes{node=\"$node\",job=\"$job\"} - node_memory_Cached_bytes{node=\"$node\",job=\"$job\"} - node_memory_Slab_bytes{node=\"$node\",job=\"$job\"} - node_memory_PageTables_bytes{node=\"$node\",job=\"$job\"} - node_memory_SwapCached_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{node=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{node=\"$node\",job=\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{node=\"$node\",job=\"$job\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"} - node_filesystem_avail_bytes{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"}",
     "legendFormat": "{% raw %}{{mountpoint}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Disk space available",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"}",
     "legendFormat": "{% raw %}{{mountpoint}} - Available{% endraw %}"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Reads completed{% endraw %}"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Writes completed{% endraw %}"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Successfully read bytes{% endraw %}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Successfully written bytes{% endraw %}"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{node=\"$node\",job=\"$job\"} [5m])",
     "legendFormat": "{% raw %}{{device}}{% endraw %}"
    }
   ]
  },
  { "title": "Storage Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Disk IOps Completed",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Reads completed{% endraw %}"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Writes completed{% endraw %}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Read bytes{% endraw %}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Written bytes{% endraw %}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{node=\"$node\",job=\"$job\"}[5m]) / irate(node_disk_reads_completed_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Read wait time avg{% endraw %}"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{node=\"$node\",job=\"$job\"}[5m]) / irate(node_disk_writes_completed_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Write wait time avg{% endraw %}"
    }
   ]
  },
  {
   "title": "Average Queue Size",
   "type": "timeseries",
   "description": "The average queue length of the requests that were issued to the device",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}}{% endraw %}"
    }
   ]
  },
  {
   "title": "Disk R/W Merged",
   "type": "timeseries",
   "description": "The number of read and write requests merged per second that were queued to the device",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Read merged{% endraw %}"
    },
    {
     "expr": "irate(node_disk_writes_merged_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Write merged{% endraw %}"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "timeseries",
   "description": "Percentage of elapsed time during which I/O requests were issued to the device (bandwidth utilization for the device). Device saturation occurs when this value is close to 100% for devices serving requests serially.  But for devices  serving requests in parallel, such as RAID arrays and modern SSDs, this number does not reflect their performance limits.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - IO{% endraw %}"
    },
    {
     "expr": "irate(node_disk_discard_time_seconds_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - discard{% endraw %}"
    }
   ]
  },
  {
   "title": "Instantaneous Queue Size",
   "type": "timeseries",
   "description": "The number of outstanding requests at the instant the sample was taken. Incremented as requests are given to appropriate struct request_queue and decremented as they finish.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_disk_io_now{node=\"$node\",job=\"$job\"}",
     "legendFormat": "{% raw %}{{device}} - IO now{% endraw %}"
    }
   ]
  },
  {
   "title": "Disk IOps Discards completed / merged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_discards_completed_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Discards completed{% endraw %}"
    },
    {
     "expr": "irate(node_disk_discards_merged_total{node=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{% raw %}{{device}} - Discards merged{% endraw %}"
    }
   ]
  },
  { "title": "Storage Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Filesystem space available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"}",
     "legendFormat": "{% raw %}{{mountpoint}} - Available{% endraw %}"
    }
   ]
  },
  {
   "title": "File Nodes Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_files_free{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"}",
     "legendFormat": "{% raw %}{{mountpoint}} - Free file nodes{% endraw %}"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_maximum{node=\"$node\",job=\"$job\"}",
     "legendFormat": "Max open files"
    },
    {
     "expr": "node_filefd_allocated{node=\"$node\",job=\"$job\"}",
     "legendFormat": "Open files"
    }
   ]
  },
  {
   "title": "File Nodes Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_files{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"}",
     "legendFormat": "{% raw %}{{mountpoint}} - File nodes total{% endraw %}"
    }
   ]
  },
  {
   "title": "Filesystem in ReadOnly / Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_readonly{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"}",
     "legendFormat": "{% raw %}{{mountpoint}} - ReadOnly{% endraw %}"
    },
    {
     "expr": "node_filesystem_device_error{node=\"$node\",job=\"$job\",device!~\"rootfs\", fstype!~\"tmpfs\"}",
     "legendFormat": "{% raw %}{{mountpoint}} - Device error{% endraw %}"
    }
   ]
  }
 ]
}