---
- name: Install components for Lake service
  hosts: server
  gather_facts: false
  environment:
    HELM_PLUGINS: '{{ helm_plugins_dir }}'
    KUBECONFIG: '{{ kubeconfig_yaml }}'
  tasks:
    - name: Install hive metastore service (HMS) with helm
      kubernetes.core.helm:
        name: hive-metastore
        chart_ref: '{{ scout_repo_dir }}/helm/lake/hive-metastore'
        values_files:
          - '{{ scout_repo_dir }}/helm/lake/hive-metastore/values.yaml'
        release_namespace: '{{ hive_namespace }}'
        release_state: present
        wait: true
        wait_timeout: 5m
        atomic: true
        values:
          env:
            - name: HIVE_METASTORE_DRIVER
              value: 'org.postgresql.Driver'
            - name: HIVE_METASTORE_JDBC_URL
              value: 'jdbc:postgresql://postgresql-cluster-rw.{{ postgres_namespace }}:5432/hive?sslmode=disable'
            - name: HIVE_METASTORE_USER
              value: '{{ postgres_user }}'
            - name: HIVE_METASTORE_PASSWORD
              value: '{{ postgres_password }}'
            - name: HIVE_METASTORE_WAREHOUSE_DIR
              value: 's3a://lake/hive'
            - name: S3_ENDPOINT
              value: '{{ s3_endpoint }}'
            - name: S3_ACCESS_KEY
              value: '{{ s3_username }}'
            - name: S3_SECRET_KEY
              value: '{{ s3_password }}'
            - name: S3_PATH_STYLE_ACCESS
              value: 'true'
            - name: REGION
              value: 'us-east-1'
            - name: HIVE_METASTORE_USERS_IN_ADMIN_ROLE
              value: 'admin'
            # All of these empty values must be present
            - name: GOOGLE_CLOUD_KEY_FILE_PATH
              value: ''
            - name: AZURE_ADL_CLIENT_ID
              value: ''
            - name: AZURE_ADL_CREDENTIAL
              value: ''
            - name: AZURE_ADL_REFRESH_URL
              value: ''
            - name: AZURE_ABFS_STORAGE_ACCOUNT
              value: ''
            - name: AZURE_ABFS_ACCESS_KEY
              value: ''
            - name: AZURE_WASB_STORAGE_ACCOUNT
              value: ''
            - name: AZURE_ABFS_OAUTH
              value: ''
            - name: AZURE_ABFS_OAUTH_TOKEN_PROVIDER
              value: ''
            - name: AZURE_ABFS_OAUTH_CLIENT_ID
              value: ''
            - name: AZURE_ABFS_OAUTH_SECRET
              value: ''
            - name: AZURE_ABFS_OAUTH_ENDPOINT
              value: ''
            - name: AZURE_WASB_ACCESS_KEY
              value: ''

    - name: Wait for Hive to be ready
      command: kubectl -n hive wait --for=condition=Available --timeout=300s deployments/hive-metastore
      register: hive_ready
      changed_when: false

    - name: Add Trino Helm repository
      kubernetes.core.helm_repository:
        name: trino
        repo_url: https://trinodb.github.io/charts

    - name: Install/Upgrade Trino Helm chart
      kubernetes.core.helm:
        name: trino
        chart_ref: trino/trino
        chart_version: ^1.38.0
        release_namespace: trino
        create_namespace: true
        release_state: present
        update_repo_cache: true
        wait: true
        wait_timeout: 5m
        atomic: true
        values:
          catalogs:
            delta: |
              connector.name=delta_lake
              hive.metastore.uri={{ hive_metastore_endpoint }}
              fs.native-s3.enabled=true
              s3.aws-access-key={{ s3_username }}
              s3.aws-secret-key={{ s3_password }}
              s3.region={{ s3_region }}
              s3.endpoint={{ s3_endpoint }}
              s3.path-style-access=true

    - name: Create Traefik Middleware to strip /superset prefix for internal traffic
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.io/v1alpha1
          kind: Middleware
          metadata:
            name: superset-strip-prefix
            namespace: kube-system
          spec:
            stripPrefix:
              prefixes:
                - /superset

    - name: Create Traefik Middleware to add X-Forwarded-Prefix to Superset traffic
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: traefik.containo.us/v1alpha1
          kind: Middleware
          metadata:
            name: superset-add-forwarded
            namespace: kube-system
          spec:
            headers:
              customRequestHeaders:
                X-Forwarded-Prefix: /superset

    - name: Add Superset Helm repository
      kubernetes.core.helm_repository:
        name: superset
        repo_url: https://apache.github.io/superset

    - name: Install/Upgrade Superset Helm chart
      kubernetes.core.helm:
        name: superset
        chart_ref: superset/superset
        chart_version: ^0.14.2
        release_namespace: superset
        create_namespace: true
        release_state: present
        update_repo_cache: true
        wait: true
        wait_timeout: 15m
        atomic: true
        values:
          extraEnv:
            SUPERSET_APP_ROOT: '/superset'
            SUPERSET_WEBSERVER_BASE_URL: https://{{ server_hostname }}/superset
          extraSecretEnv:
            SUPERSET_SECRET_KEY: '{{ superset_secret }}'
          ingress:
            enabled: true
            ingressClassName: traefik
            path: /superset
            hosts:
              - '{{ server_hostname }}'
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: >
                kube-system-superset-strip-prefix@kubernetescrd,
                kube-system-superset-add-forward@kubernetescrd
          postgresql:
            enabled: false
          supersetNode:
            connections:
              db_host: 'postgresql-cluster-rw.{{ postgres_namespace }}'
              db_port: '5432'
              db_user: '{{ postgres_user }}'
              db_pass: '{{ postgres_password }}'
              db_name: superset
          configOverrides:
            prefix: |
              ENABLE_PROXY_FIX = True
              APPLICATION_ROOT = '/superset'
              SUPERSET_WEBSERVER_BASE_URL = 'https://{{ server_hostname }}/superset'
              SESSION_COOKIE_PATH = '/superset'
              WTF_CSRF_COOKIE_PATH = '/superset'
          extraConfigs:
            import_datasources.yaml: |
              databases:
                - database_name: scout
                  sqlalchemy_uri: trino://trino@trino.trino:8080/delta
                  allow_file_upload: true
          bootstrapScript: |
            #!/bin/bash
            # Install system-level dependencies
            apt-get update && apt-get install -y \
              python3-dev \
              build-essential \
              pkg-config

            # Install required Python packages
            pip install \
              authlib \
              psycopg2-binary \
              pyhive \
              trino

            {% raw %}
            if [ ! -f ~/bootstrap ]; then echo 'Running Superset with uid {{ .Values.runAsUser }}' > ~/bootstrap; fi
            {% endraw %}