auth.method=openid
type=openid
provider.id=keycloak
name=Scout SSO
auto.enabled=true
auto.verified=true

siteUrl=https://xnat.dev03.tag.rcif.io
preEstablishedRedirUri=/openid-login

openid.keycloak.clientId=xnat
openid.keycloak.clientSecret=a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6
openid.keycloak.accessTokenUri=https://keycloak.dev03.tag.rcif.io/realms/scout/protocol/openid-connect/token
openid.keycloak.userAuthUri=https://keycloak.dev03.tag.rcif.io/realms/scout/protocol/openid-connect/auth
openid.keycloak.userInfoUri=https://keycloak.dev03.tag.rcif.io/realms/scout/protocol/openid-connect/userinfo
openid.keycloak.scopes=openid,profile,email
openid.keycloak.shouldFilterEmailDomains=false
openid.keycloak.forceUserCreate=true
openid.keycloak.emailProperty=email
openid.keycloak.givenNameProperty=given_name
openid.keycloak.familyNameProperty=family_name
openid.keycloak.pkceEnabled=true
openid.keycloak.usernamePattern=[providerId]-[sub]
openid.keycloak.link=<a href="/openid-login?providerId=keycloak">Sign in with Scout</a>
