{{- if and .Values.auth.keycloak.enabled (not .Values.auth.keycloak.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "launchpad.fullname" . }}-keycloak-secret
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.auth.keycloak.clientSecret | b64enc }}
{{- end }}
{{- if and .Values.auth.keycloak.enabled (not .Values.auth.existingNextAuthSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "launchpad.fullname" . }}-nextauth-secret
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.auth.nextAuthSecret | b64enc }}
{{- end }}