{{- if or .Values.databaseUrl .Values.devSharedSecret .Values.trinoCaCert .Values.trinoAuthClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "report-viewer-service.fullname" . }}
  labels:
    {{- include "report-viewer-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.databaseUrl }}
  REPORT_VIEWER_DATABASE_URL: {{ .Values.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.devSharedSecret }}
  REPORT_VIEWER_DEV_SHARED_SECRET: {{ .Values.devSharedSecret | quote }}
  {{- end }}
  {{- if .Values.trinoAuthClientSecret }}
  REPORT_VIEWER_TRINO_AUTH_CLIENT_SECRET: {{ .Values.trinoAuthClientSecret | quote }}
  {{- end }}
  {{- if .Values.trinoCaCert }}
  ca.crt: {{ .Values.trinoCaCert | quote }}
  {{- end }}
{{- end }}
