{{- if or .Values.databaseUrl .Values.devSharedSecret .Values.trinoCaCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datasets-service.fullname" . }}
  labels:
    {{- include "datasets-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.databaseUrl }}
  DATASETS_DATABASE_URL: {{ .Values.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.devSharedSecret }}
  DATASETS_DEV_SHARED_SECRET: {{ .Values.devSharedSecret | quote }}
  {{- end }}
  {{- if .Values.trinoCaCert }}
  ca.crt: {{ .Values.trinoCaCert | quote }}
  {{- end }}
{{- end }}
