{{- if .Values.serviceAccount.create -}}
# aws only (serviceAccount.create=true): IRSA SA for OPA's S3 bundle reads.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scout-opa.serviceAccountName" . }}
  labels:
    {{- include "scout-opa.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
