{
 "title": "HL7 Ingest",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "HL7 Files Ingested",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', date) AS time,\n  COUNT(*)                AS count\nFROM recent_hl7_files\nWHERE $__timeFilter(date)\n  AND status != 'failed'\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "HL7 Ingest Errors (Log Scale)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', date) AS time,\n  COUNT(*)                AS count\nFROM recent_hl7_files\nWHERE $__timeFilter(date)\n  AND status = 'failed'\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT h.date,\n       fs.file_path,\n       fs.error_message,\n       fs.status,\n       fs.processed_at\nFROM hl7_files h\nJOIN (\n    SELECT DISTINCT ON (file_path)\n           file_path,\n           error_message,\n           status,\n           processed_at\n    FROM   file_statuses\n    WHERE  type = 'HL7'\n    ORDER  BY file_path, processed_at DESC          -- DESC is what makes it “latest”\n) AS fs\nON fs.file_path = h.hl7_file_path\nWHERE $__timeFilter(h.date) and status = 'failed'"
    }
   ]
  },
  {
   "title": "HL7 Listener Log Errors",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (file_path)\n    file_path,\n    error_message,\n    status,\n    processed_at\nFROM   file_statuses\nWHERE  type = 'Log' and status = 'failed'\nORDER  BY file_path, processed_at DESC          -- DESC is what makes it “latest”"
    }
   ]
  }
 ]
}