{
 "title": "Temporal",
 "description": "Temporal Server Metrics Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "frontend,history,matching,worker"
   },
   { "name": "Client", "query": "frontend,history,matching" }
  ]
 },
 "panels": [
  { "title": "Temporal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!=\"\" ,namespace=~\"temporal|orchestration-workers\"}[5m])) by (namespace)\n+ on (namespace)\n(sum(rate(windows_container_cpu_usage_seconds_total{container_id!=\"\", cluster=\"$cluster\", namespace=~\"temporal|orchestration-workers\"}[5m]) * on (container_id) group_left (container, pod, namespace) max by (container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", namespace=~\"temporal|orchestration-workers\"}) OR kube_namespace_created * 0) by (namespace))\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod!=\"\", namespace=~\"temporal|orchestration-workers\"}) by (namespace)\n+ on (namespace)\n(sum(windows_container_memory_usage_commit_bytes{container_id!=\"\" ,namespace=~\"temporal|orchestration-workers\"} * on (container_id) group_left (container, pod, namespace) max by (container, container_id, pod, namespace) (kube_pod_container_info{container_id!=\"\", namespace=~\"temporal|orchestration-workers\"}) OR kube_namespace_created * 0) by (namespace))\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"temporal|orchestration-workers\", pod!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"temporal|orchestration-workers\", pod!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Service Availability (Based on Frontend Calls)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (sum(rate(service_errors[2m]) OR on() vector(0)) / sum(rate(service_requests[2m])) * 100)",
     "legendFormat": "availability"
    }
   ]
  },
  {
   "title": "Persistence Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (sum (rate(persistence_errors[2m]) OR on() vector(0)) /sum (rate(persistence_requests[2m])) * 100)",
     "legendFormat": "availability"
    }
   ]
  },
  {
   "title": "External Events",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(service_requests{operation=~\"StartWorkflowExecution|SignalWorkflowExecution|SignalWithStartWorkflowExecution\"}[2m]))"
    }
   ]
  },
  {
   "title": "Workflow Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(service_requests{ operation=\"AddWorkflowTask\"}[2m]))",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(rate(service_requests{ operation=\"RecordWorkflowTaskStarted\"}[2m]))",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(rate(service_requests{ operation=\"RespondWorkflowTaskCompleted\"}[2m]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(rate(service_requests{ operation=\"RespondWorkflowTaskFailed\"}[2m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(schedule_to_start_timeout{ operation=\"TimerActiveTaskWorkflowTimeout\"}[2m]))",
     "legendFormat": "Sticky Task Queue Timeout"
    },
    {
     "expr": "sum(rate(start_to_close_timeout{ operation=\"TimerActiveTaskWorkflowTimeout\"}[2m]))",
     "legendFormat": "Workflow Task Timeout"
    }
   ]
  },
  {
   "title": "Activities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(service_requests{operation=\"AddActivityTask\"}[2m]))",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(rate(service_requests{operation=\"RecordActivityTaskStarted\"}[2m]))",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(rate(service_requests{operation=~\"RespondActivityTaskCompleted|RespondActivityTaskFailed|RespondActivityTaskCanceled\"}[2m]))",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shard Rebalancing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(membership_changed_count[2m]))",
     "legendFormat": "membership_changed"
    },
    {
     "expr": "sum(rate(sharditem_created_count[2m]))",
     "legendFormat": "shard_item_created"
    },
    {
     "expr": "sum(rate(sharditem_removed_count[2m]))",
     "legendFormat": "shard_item_removed"
    },
    {
     "expr": "sum(rate(shard_closed_count[2m]))",
     "legendFormat": "shard_closed"
    }
   ]
  },
  {
   "title": "Shard Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "numshards_gauge", "legendFormat": "{{ kubernetes_pod_name }}" }
   ]
  },
  {
   "title": "Lock Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(lock_latency_bucket[5m]))) * 1000",
     "legendFormat": "Shard"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (temporal_service_type) (restarts)",
     "legendFormat": "{{ temporal_service_type }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "num_goroutines", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "memory_allocated", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "memory_heap", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 52 },
   "targets": [
    { "expr": "memory_stack", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "GC Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (rate(memory_num_gc[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(memory_gc_pause_ms_bucket[5m])) by (kubernetes_pod_name, le))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "State Transition",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(state_transition_count_count[2m]))",
     "legendFormat": "state transition"
    },
    {
     "expr": "sum(rate(sharditem_created_count[2m]))",
     "legendFormat": "shard_item_created"
    },
    {
     "expr": "sum(rate(sharditem_removed_count[2m]))",
     "legendFormat": "shard_item_removed"
    },
    {
     "expr": "sum(rate(shard_closed_count[2m]))",
     "legendFormat": "shard_closed"
    }
   ]
  },
  { "title": "Workflow Completion Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Workflow Completion Overview",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(workflow_success{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(workflow_failed{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(workflow_timeout{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "timedout"
    },
    {
     "expr": "sum(rate(workflow_terminate{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "terminate"
    },
    {
     "expr": "sum(rate(workflow_cancel{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "cancelled"
    }
   ]
  },
  {
   "title": "Workflow Success By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(workflow_success{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Workflow Failed By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(workflow_failed{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "{{ namespace }} "
    }
   ]
  },
  {
   "title": "Workflow Timedout By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(workflow_timeout{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "{{ namespace }} "
    }
   ]
  },
  {
   "title": "Workflow Terminate By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(workflow_terminate{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "{{ namespace }} "
    }
   ]
  },
  {
   "title": "Workflow Cancelled By Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum by (namespace) (rate(workflow_cancel{ operation=\"CompletionStats\"}[5m]))",
     "legendFormat": "{{ namespace }} "
    }
   ]
  },
  { "title": "Overview - $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Service RequestsVs Errors ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum (rate(service_requests[5m]))",
     "legendFormat": "requests"
    },
    { "expr": "sum (rate(service_errors[5m]))", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Service Requests Per Operation ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 97 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(service_requests[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Service Errors Break Down ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sum(rate(service_errors_entity_not_found[5m]) OR on() vector(0))",
     "legendFormat": "Entity Not Found"
    },
    {
     "expr": "sum(rate(service_errors_execution_already_started[5m]) OR on() vector(0))",
     "legendFormat": "Execution Already Started"
    },
    {
     "expr": "sum(rate(service_errors_resource_exhausted[5m]) OR on() vector(0))",
     "legendFormat": "Resource Exhausted"
    }
   ]
  },
  {
   "title": "Service Errors By Operation ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 97 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(service_errors[5m]))"
    }
   ]
  },
  {
   "title": "Service Latency ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket[5m])) by (service_name, operation, le))",
     "legendFormat": "{{service_name}}:{{operation}}"
    }
   ]
  },
  {
   "title": "Poll Sync Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (task_type) (rate(poll_success_sync[5m])) / sum by (task_type) (rate(poll_success[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schedule to Start Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(temporal_workflow_task_schedule_to_start_latency_bucket[5m])))",
     "legendFormat": "Workflow"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(temporal_activity_schedule_to_start_latency_bucket[5m])))",
     "legendFormat": "Activity"
    }
   ]
  },
  { "title": "Persistence - $Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Persistence Requests Vs Errors ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "sum (rate(persistence_requests[5m]) OR on() vector(0))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum (rate(persistence_errors[5m]) OR on() vector(0))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Persistence Requests Per Operation ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 130 },
   "targets": [
    {
     "expr": " sum by (operation) (rate(persistence_requests[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Persistence Errors By Operation ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 130 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(persistence_errors[5m]))"
    }
   ]
  },
  {
   "title": "Persistence Latency ($Service)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(persistence_latency_bucket[5m])) by (service_name, operation, le))",
     "legendFormat": "{{service_name}}:{{operation}}"
    }
   ]
  },
  { "title": "Service Client - $Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Requests Vs Errors ($Service -> $Client)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 155 },
   "targets": [
    { "expr": "sum(rate(client_requests[5m]))", "legendFormat": "requests" },
    { "expr": "sum(rate(client_errors[5m]))", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Client Requests Per Operation ($Service -> $Client)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 155 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(client_requests[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors By Operation ($Service -> $Client)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 155 },
   "targets": [
    {
     "expr": "sum by (operation) (rate(client_errors[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Client Latency ($Service -> $Client)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(client_latency_bucket[5m])) by (operation, le))",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}